### ISSUE TITLE
Atualizar o documento de visão 

### ISSUE THREAD

**Issue by lucasqueiroz23** [mdsreq-fga-unb/2022.2-AeroWiki#3]
Devemos melhorar o doc de visão tendo, como base, o seguinte feedback: 

- O que é gestão do conhecimento
- Se o produto realmente deseja fazer isso 
- Sistemas gerenciadores de conhecimento - geralmente soluções pagas
- Ao contrário de - [nome da aplicação]
- Especificar objetivos(quanto mais interpretativo estiver, pior)
- Ser objetivo
- Devemos aprender a diferença entre gestão do conhecimento e gestão da informação

**Comment by ArthurFerreiraRodrigues** [comment]
Me marcaram errado.
